### ISSUE TITLE
Support for Laravel 6.x

### ISSUE THREAD

**Issue by faiverson** [marvinlabs/laravel-luhn#7]
The current version doesn't support Laravel 6.x since the dependency illuminate/support is flag to an old version.
Updating the dependency should be enough

**Comment by faiverson** [comment]
Do I need to send a PR?

**Comment by vpratfr** [comment]
That would be great. Do not forget to run tests too.

**Comment by metadiablo-glyph** [comment]
Any progress on this?

**Comment by vpratfr** [comment]
1.0.5 already supports 6.x

Feel free to send a pr for 7.x
